### ISSUE TITLE
node Notready after applying smtp ingress

### ISSUE THREAD

**Issue by outbackdingo** [postalhq/k8s-hippo#1]
as soon as i apply this my node goes into notready mode using metallb and 
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 212.32.234.181-212.32.234.182

is a 3 node cluster, deployed with kubespray, so is this known, or have i somehow misconfigured metallb ?

kind: Service
apiVersion: v1
metadata:
  name: smtp
  {% if config.smtpMetalLBAddressPool %}
  annotations:
    metallb.universe.tf/address-pool: {{ config.smtpMetalLBAddressPool}}
  {% endif %}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 25
      targetPort: 2525
  selector:
    process_type: smtp

**Comment by adamcooke** [comment]
I don't see how either of these things would cause a node to become NotReady.

The service object you've pasted is the template. You'd be better looking at the compiled version using `hippo [stage] objects -t services --to-apply` or `kubectl -n [namespace] get svc smtp -o yaml`

**Comment by outbackdingo** [comment]
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"production","app.kubernetes.io/managed-by":"hippo","app.kubernetes.io/name":"postal"},"name":"smtp","namespace":"postal-production"},"spec":{"externalTrafficPolicy":"Local","ports":[{"port":25,"targetPort":2525}],"selector":{"process_type":"smtp"},"type":"LoadBalancer"}}
  creationTimestamp: "2020-03-26T09:45:01Z"
  labels:
    app.kubernetes.io/instance: production
    app.kubernetes.io/managed-by: hippo
    app.kubernetes.io/name: postal
  name: smtp
  namespace: postal-production
  resourceVersion: "96998"
  selfLink: /api/v1/namespaces/postal-production/services/smtp
  uid: 8c83299f-200c-45c0-b2df-ea50e159c056
spec:
  clusterIP: 10.233.33.205
  externalTrafficPolicy: Local
  healthCheckNodePort: 30409
  ports:
  - nodePort: 30896
    port: 25
    protocol: TCP
    targetPort: 2525
  selector:
    process_type: smtp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 212.32.234.181

**Comment by adamcooke** [comment]
That all looks fine to me. I don't think this issue can be related to that service object so not really something I can help with.

**Comment by outbackdingo** [comment]
welp thats a fail.... seesm hippo-k8s postal requires LoadBalancer which seems broken on kubespray with ipvs and layer 2 .... so how can i deploy this on k8s now? which is what appears to be making the node fallover.
